### DISCUSSION TITLE
How to force ingest a source?

### DISCUSSION THREAD

**Discussion by tedpelas** [irrdnet/irrd#795] [Q&A]
Two of our local script-generated sources stopped updating; any ideas on how we can force IRRd to ingest new data?
No attempts for 10 days.

Here is our config:
```
    NICBR:
      authoritative: false
      keep_journal: false
      import_serial_source: 'file:///var/spool/irrd/NICBR.CURRENTSERIAL'
      import_source: 'file:///var/spool/irrd/nicbr.db.gz'
```

Do not find any other way to force-pull the source except to reload the application?

Thanks
