### ISSUE TITLE
Synthesize NRTM history when using `irrd_load_database`

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#271]
We are using IRRd 4 to make generated RPSL databases available via WHOIS. Other folks might want to track those databases, but we don't have a NRTM history for the databases that are loaded via `irrd_load_database`.

When using a command like `irrd_load_database --irrd_pidfile /home/irrd/irrd.pid --serial $(SERIAL) --source REGISTROBR registrobr.db`, the IRRd4 daemon should synthesize the history from the previous SERIAL towards the current number in `$(SERIAL)` (which from this example is a M4 macro that does +1 every time the macro is run).

If the serial provided to `irr_load_database` is lower than the serial stored in the IRRd 4 database, an error should be thrown that can only be override when using a new to-be-created `--force` command line argument to `irr_load_database`

**Comment by job** [comment]
The configuration from this example is:

````
irrd:
    sources_default:
        - REGISTROBR
    sources:
        REGISTROBR:
            nrtm_access_list: generic_nrtm_access
            import_serial_source: file:///home/irrd/routing_sources/registrobr/REGISTROBR.CURRENTSERIAL
            import_source: file:///home/irrd/routing_sources/registrobr/registrobr.db
```
