### ISSUE TITLE
Serials in !j queries may be incorrect in 4.1

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd#322]
As reported by @ccaputo:

In addition, while I notice new data is available via queries, I am not seeing serial numbers increase due to NRTM updates as indicated by ```!j-*```.  For example, rr.ntt.net currently reports ```NTTCOM:Y:1002835-1202996:1202995``` while my local instance reports ```NTTCOM:N:1202992-1202992``` and my log contains:

```
2020-06-11 07:48:05,929 irrd[29192]: [irrd.mirroring.nrtm_operation#INFO] Completed NRTM operation NTTCOM/1202996/ADD/route/46.8.96.0/22AS21859, RPKI status NOT_FOUND
```

and a query for 46.8.96.0 accurately reveals:

```
route:          46.8.96.0/22
descr:          CMI IP Transit
origin:         AS21859
mnt-by:         MAINT-CMI-INT-HK
changed:        qas_support@cmi.chinamobile.com 20200611
source:         NTTCOM
```

Config for NTTCOM is:

```
        NTTCOM:
            import_serial_source: 'ftp://rr1.ntt.net/nttcomRR/NTTCOM.CURRENTSERIAL'
            import_source: 'ftp://rr1.ntt.net/nttcomRR/nttcom.db.gz'
            nrtm_host: rr.ntt.net
            import_timer: 300
            object_class_filter:
                - as-set
                - route
                - route6
                - route-set
```

Are the above errors and the serial number not updating related?  How to fix both?

I have RPKI disabled with ```roa_source: null```.

**IRRd version you are running**
4.1.0b3 (24cf8812cabe46ea7eaff1c43c9b6a029c30f11c)
