### ISSUE TITLE
Not able to access HTTP status page

### ISSUE THREAD

**Issue by forkwhilefork** [irrdnet/irrd#441]
After upgrading from 4.1.0 to the latest git master (784fc44f965f050ef49b70985452d52fea3ba140), I am no longer able to access the HTTP status page at /v1/status. I see this entry in the log:
```
2020-12-03 03:36:15,695 irrd[10215]: [irrd.server.access_check#INFO] Rejecting request, access list empty or undefined: 23.147.64.72
2020-12-03 03:36:15,696 irrd[10215]: [uvicorn.access#INFO] ::ffff:23.147.64.72:48822 - "GET /v1/status/ HTTP/1.1" 403
```
(23.147.64.72 is where I am trying to access it from.)

My config file has this section, which has not changed since upgrading:
```
    access_lists:
        http_database_status:
            - '::/32'
            - '127.0.0.1'
            - '23.147.64.72'

    server:
        http:
            access_list: http_database_status
            interface: '::0'
            port: 8080
        whois:
            interface: '::0'
            max_connections: 50
            port: 8043
```

I checked the "latest" docs and don't see anything that needs to be done differently in the config to make the ACL work. This looks like either a bug, or documentation needs to be updated.
