### ISSUE TITLE
force_reload doesn't ignore serial number

### ISSUE THREAD

**Issue by rubenskuhl** [irrdnet/irrd#492]
**Describe the bug**
irrd_mirror_force_reload sets a force reload flag on a mirror. But it still takes the serial number into account, so even if a configuration has changed that would change the records, the mirror is still not reloaded.

**To Reproduce**
Setup a mirror
Change a config that would make the mirror different, like adding more input files to input source.

**Expected behaviour**
Force reload should disregard the serial number and proceed. 

**IRRd version you are running**
E.g. 4.2.0b1

**Additional context**
2021-04-19 15:25:15,976 irrd[58877]: [irrd.storage.database_handler#INFO] force_reload flag set for APNIC, serial synchronisation based on current settings: False

**Comment by mxsasha** [comment]
Did you see that it did not work, or did you conclude that from the log message? Because reading the code, it looks like it should work, but the log message is definitely confusing.

What that log actually means is:
* the force_reload flag was successfully set for APNIC
* based on the current settings, [serial synchronisation](https://irrd.readthedocs.io/en/latest/users/mirroring/) will be disabled after the reload

However, it reads like the force reload flag was set to False.

**Comment by rubenskuhl** [comment]
After fixing the source definition, a new error message appeared:
[irrd.mirroring.mirror_runners_import#INFO] Running full RPSL import of APNIC from ['https://ftp.apnic.net/apnic/whois/apnic.db.as-block.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.as-set.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.aut-num.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.domain.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.filter-set.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.inet-rtr.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.irt.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.key-cert.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.mntner.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.organisation.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.peering-set.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.role.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.route-set.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.route.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.route6.gz', 'https://ftp.apnic.net/apnic/whois/apnic.db.rtr-set.gz'], serial from ['https://ftp.apnic.net/apnic/whois/APNIC.CURRENTSERIAL']
2021-04-19 16:50:54,547 irrd[523019]: [irrd.mirroring.mirror_runners_import#ERROR] An exception occurred while attempting a mirror update or initial import for APNIC: 'DottedList' object has no attribute 'decode'

**Comment by mxsasha** [comment]
> 2021-04-19 16:50:54,547 irrd[523019]: [irrd.mirroring.mirror_runners_import#ERROR] An exception occurred while attempting a mirror update or initial import for APNIC: 'DottedList' object has no attribute 'decode'

This is definitely a bug. Possibly caused by a configuration issue, but then the bug is that not being properly detected and logged.

Are there lines after that message with a traceback of where this originated?

**Comment by rubenskuhl** [comment]
> > 2021-04-19 16:50:54,547 irrd[523019]: [irrd.mirroring.mirror_runners_import#ERROR] An exception occurred while attempting a mirror update or initial import for APNIC: 'DottedList' object has no attribute 'decode'
> 
> This is definitely a bug. Possibly caused by a configuration issue, but then the bug is that not being properly detected and logged.
> 
> Are there lines after that message with a traceback of where this originated?

No, the 523019 index has only those two messages and index 523020 and so forth are of different instances. The complete SOURCE defintion is:
```
       APNIC:
            authoritative: false
#            keep_journal: true
            import_serial_source:
                 - 'https://ftp.apnic.net/apnic/whois/APNIC.CURRENTSERIAL'
            import_source:
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.as-block.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.as-set.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.aut-num.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.domain.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.filter-set.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.inet-rtr.gz'
#                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.inet6num.gz'
#                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.inetnum.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.irt.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.key-cert.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.mntner.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.organisation.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.peering-set.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.role.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.route-set.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.route.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.route6.gz'
                 - 'https://ftp.apnic.net/apnic/whois/apnic.db.rtr-set.gz'
#            nrtm_host: whois.apnic.net
#            nrtm_port: 43
            rpki_excluded: true
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
```
