### ISSUE TITLE
Mirroring with IRRD: manually load and update source data doesn't work as expected

### ISSUE THREAD

**Issue by Justin-APNIC** [irrdnet/irrd#809]
**Describe the bug**
Hi, i am trying to use IRRD as our NRTM client and server. I load a db file for a source with an initial serial number, then update the db with new db file, but the serial number is not increased from the initial number, from 1 instead. Also, the NRTM query response doesn't work as expected as well. I am not sure whether i did something wrong. Could you have a look? Thanks

**To Reproduce**
**Configuration file**
```
irrd:
    database_url: 'postgresql://irrd:irrd@localhost:5432/irrd'
    redis_url: 'redis://localhost:6379'
    piddir: /irrd/irrd-venv/var/run
    user: justin.yang
    group: admin

    access_lists:
        generic_nrtm_access:
            - '0.0.0.0/0'

    server:
        http:
            interface: 127.0.0.1
            port: 8080
        whois:
            interface: 127.0.0.1
            port: 43
    email:
        footer: ''
        notification_header: |
            This is to notify you of changes in the {sources_str} database
            or object authorisation failures.

            You may receive this message because you are listed in
            the notify attribute on the changed object(s), because
            you are listed in the mnt-nfy or upd-to attribute on a maintainer
            of the object(s), or the upd-to attribute on the maintainer of a
            parent of newly created object(s).
        from: example@example.com
        smtp: localhost

    auth:
        gnupg_keyring: /irrd/irrd-venv/gnupg-keyring

    log:
        logfile_path: /irrd/irrd-venv/var/log/irrd.log
        level: DEBUG

    rpki:
        roa_source: null

    sources:
        JPNIC:
            authoritative: true
            keep_journal: true
            nrtm_access_list: generic_nrtm_access`
```

**Load initial data**

```
 % cat jpnic-test.db 
inetnum:        27.96.54.48 - 27.96.54.55
netname:        Y2JI-NET
descr:          y2ji, Inc.
country:        JP
admin-c:        TT53002JP
tech-c:         TT53002JP
remarks:        This information has been partially mirrored by APNIC from
remarks:        JPNIC. To obtain more specific information, please use the
remarks:        JPNIC WHOIS Gateway at
remarks:        http://www.nic.ad.jp/en/db/whois/en-gateway.html or
remarks:        whois.nic.ad.jp for WHOIS client. (The WHOIS client
remarks:        defaults to Japanese output, use the /e switch for English
remarks:        output)
last-modified:  2023-07-01T19:50:03Z
source:         JPNIC
```

`./bin/irrd_load_database --source JPNIC ~/Downloads/jpnic-test.db --serial 10
`

**Update data**

```
 % cat jpnic-test-update.db
inetnum:        27.96.54.48 - 27.96.54.55
netname:        Y2JI-NET
descr:          y2ji, Inc.
country:        JP
admin-c:        TT53002JP
tech-c:         TT53002JP
remarks:        This information has been partially mirrored by APNIC from
remarks:        JPNIC. To obtain more specific information, please use the
remarks:        JPNIC WHOIS Gateway at
remarks:        http://www.nic.ad.jp/en/db/whois/en-gateway.html or
remarks:        whois.nic.ad.jp for WHOIS client. (The WHOIS client
remarks:        defaults to Japanese output, use the /e switch for English
remarks:        output)
last-modified:  2023-07-01T19:50:03Z
source:         JPNIC

aut-num:        AS63795
as-name:        ROUTEL
descr:          RoutelNet
import:         from AS59103 100 accept ANY
import:         from AS59105 100 accept ANY
export:         to AS59103 announce AS63795
export:         to AS59105 announce AS63795
country:        JP
admin-c:        JP00227706
tech-c:         JP00227706
last-modified:  2022-05-27T19:17:08Z
source:         JPNIC
```

`./bin/irrd_update_database --source JPNIC ~/Downloads/jpnic-test-update.db
`

**NRTM query response**
```

% telnet localhost 43                                                                                                            
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
-g JPNIC:3:1-LAST
%START Version: 3 JPNIC 1-3

ADD 1

aut-num:        AS63795
as-name:        ROUTEL
descr:          RoutelNet
import:         from AS59103 100 accept ANY
import:         from AS59105 100 accept ANY
export:         to AS59103 announce AS63795
export:         to AS59105 announce AS63795
country:        JP
admin-c:        JP00227706
tech-c:         JP00227706
source:         JPNIC
last-modified:  2023-07-03T23:01:58Z

ADD 2

aut-num:        AS63795
as-name:        ROUTEL
descr:          RoutelNet
import:         from AS59103 100 accept ANY
import:         from AS59105 100 accept ANY
export:         to AS59103 announce AS63795
export:         to AS59105 announce AS63795
country:        JP
admin-c:        JP00227706
tech-c:         JP00227706
source:         JPNIC
last-modified:  2023-07-03T23:01:58Z

ADD 3

inetnum:        27.96.54.48 - 27.96.54.55
netname:        Y2JI-NET
descr:          y2ji, Inc.
country:        JP
admin-c:        TT53002JP
tech-c:         TT53002JP
remarks:        This information has been partially mirrored by APNIC from
remarks:        JPNIC. To obtain more specific information, please use the
remarks:        JPNIC WHOIS Gateway at
remarks:        http://www.nic.ad.jp/en/db/whois/en-gateway.html or
remarks:        whois.nic.ad.jp for WHOIS client. (The WHOIS client
remarks:        defaults to Japanese output, use the /e switch for English
remarks:        output)
source:         JPNIC
last-modified:  2023-07-03T23:01:58Z

%END JPNIC
```

Connection closed by foreign host.

**Expected behaviour**
The NTM query response should return just one ADD for aut-num: AS63795 with serial 11

**IRRd version you are running**
E.g. 4.3.0-POST1
